/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jnidemo_JNITest */

#ifndef _Included_com_example_jnidemo_JNITest
#define _Included_com_example_jnidemo_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jnidemo_JNITest
 * Method:    getStrFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jnidemo_JNITest_getStrFromJNI
  (JNIEnv *, jclass);

/*
 * Class:     com_example_jnidemo_JNITest
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_jnidemo_JNITest_add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_jnidemo_JNITest
 * Method:    getStrParse
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jnidemo_JNITest_getStrParse
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_jnidemo_JNITest
 * Method:    parseIntArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_jnidemo_JNITest_parseIntArray
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_example_jnidemo_JNITest
 * Method:    callbackvoidmethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jnidemo_JNITest_callbackvoidmethod
  (JNIEnv *, jclass);

/*
 * Class:     com_example_jnidemo_JNITest
 * Method:    callbackintmethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jnidemo_JNITest_callbackintmethod
  (JNIEnv *, jclass);

/*
 * Class:     com_example_jnidemo_JNITest
 * Method:    callbackstringmethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jnidemo_JNITest_callbackstringmethod
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
